plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Firebase Cloud Messaging (family alert push) is opt-in at build time.
//
// The google-services plugin fails the build outright when it cannot find a
// google-services.json, and that file can only be generated by whoever owns
// the Firebase project. Applying it unconditionally would mean nobody could
// build this app without first setting up Firebase — too high a price for one
// optional feature. So it is applied only when the file is actually there:
// drop your google-services.json into android/app/ and push lights up on the
// next build, with no code change. Without it the app builds and runs exactly
// as before and PushNotificationService reports itself unavailable.
if (file("google-services.json").exists()) {
    apply(plugin = "com.google.gms.google-services")
} else {
    logger.lifecycle(
        "ScamShield: android/app/google-services.json not found - building without " +
            "Firebase push notifications. Family alerts still work; they just arrive " +
            "when the app is next opened rather than being pushed."
    )
}

android {
    namespace = "com.example.scamshield"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.scamshield"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        // mobile_scanner requires API 23+; flutter_local_notifications requires API 24+.
        minSdk = maxOf(flutter.minSdkVersion, 24)
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}
